"""
backtesting/models.py — Strongly typed domain models for APEX-QUANT Backtesting Subsystem.

Defines data structures for orders, fills, accounting snapshots, performance metrics,
and simulation results with strict invariants.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional
import pandas as pd


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


@dataclass
class SimulatedOrder:
    """Represents a simulated order generated by the rebalance engine."""
    order_id: str
    timestamp: pd.Timestamp
    symbol: str
    side: OrderSide
    quantity: int
    price: float
    notional: float


@dataclass
class SimulatedFill:
    """Represents the simulated fill of an order, including friction and costs."""
    order_id: str
    timestamp: pd.Timestamp
    symbol: str
    side: OrderSide
    requested_quantity: int
    executed_quantity: int
    unfilled_quantity: int
    execution_price: float
    notional: float
    slippage: float
    transaction_cost: float
    total_cost: float
    status: OrderStatus = OrderStatus.FILLED
    rejection_reason: Optional[str] = None


@dataclass
class HoldingPosition:
    """Point-in-time state of an individual equity holding in the portfolio."""
    symbol: str
    shares: int
    average_cost: float
    current_price: float
    market_value: float
    weight: float
    unrealized_pnl: float
    sector: Optional[str] = None


@dataclass
class PortfolioSnapshot:
    """Comprehensive state of the portfolio at a discrete historical timestamp."""
    timestamp: pd.Timestamp
    cash: float
    positions: Dict[str, HoldingPosition]
    gross_exposure: float
    portfolio_value: float
    daily_return: float
    cumulative_return: float
    peak_value: float
    drawdown: float
    realized_pnl: float
    unrealized_pnl: float
    fees_paid: float
    slippage_paid: float
    turnover: float
    is_rebalance_bar: bool = False


@dataclass
class BacktestMetrics:
    """Realized quantitative performance and risk metrics over the backtest timeline."""
    total_return: float
    annualized_return: float
    cagr: float
    annualized_volatility: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    max_drawdown_duration_days: int
    calmar_ratio: float
    win_rate: float
    profit_factor: float
    total_turnover: float
    total_fees: float
    total_slippage: float
    rebalance_count: int
    trade_count: int
    average_positions: float
    average_cash_weight: float
    average_turnover: float = 0.0
    annualized_turnover: float = 0.0
    calendar_cagr: float = 0.0



@dataclass
class WalkForwardPeriodResult:
    """Performance evaluation for a distinct chronological sub-period."""
    period_id: str
    start_date: str
    end_date: str
    total_return: float
    annualized_volatility: float
    sharpe_ratio: float
    max_drawdown: float
    turnover: float
    total_costs: float


@dataclass
class BacktestResult:
    """Complete, serializable artifact generated by the BacktestEngine."""
    config: Any
    equity_curve: pd.DataFrame
    snapshots: List[PortfolioSnapshot]
    fills: List[SimulatedFill]
    rebalances: List[Dict]
    metrics: BacktestMetrics
    benchmark_curves: Dict[str, pd.Series] = field(default_factory=dict)
    walk_forward_periods: List[WalkForwardPeriodResult] = field(default_factory=list)
    walk_forward_audit_logs: List[Any] = field(default_factory=list)


    def to_trades_dataframe(self) -> pd.DataFrame:
        """Export all simulated fills into a pandas DataFrame."""
        if not self.fills:
            return pd.DataFrame(columns=[
                "timestamp", "order_id", "symbol", "side", "executed_quantity",
                "execution_price", "notional", "transaction_cost", "slippage", "total_cost", "status"
            ])
        records = [
            {
                "timestamp": f.timestamp,
                "order_id": f.order_id,
                "symbol": f.symbol,
                "side": f.side.value,
                "requested_quantity": f.requested_quantity,
                "executed_quantity": f.executed_quantity,
                "unfilled_quantity": f.unfilled_quantity,
                "execution_price": f.execution_price,
                "notional": f.notional,
                "transaction_cost": f.transaction_cost,
                "slippage": f.slippage,
                "total_cost": f.total_cost,
                "status": f.status.value,
                "rejection_reason": f.rejection_reason,
            }
            for f in self.fills
        ]
        return pd.DataFrame.from_records(records)
