import React from "react";
import { Card, CardHeader, CardTitle, CardContent } from "../../components/ui/Card";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "../../components/ui/Table";
import { MOCK_SIGNALS } from "../../data/mock";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "../../components/ui/Dialog";
import { Tooltip, TooltipTrigger, TooltipContent } from "../../components/ui/Tooltip";
import { Info } from "lucide-react";
import { Badge } from "../../components/ui/Badge";

export default function Signals() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold tracking-tight text-zinc-100">Quantitative Signals</h1>
      
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Symbol</TableHead>
                <TableHead>Signal</TableHead>
                <TableHead className="text-right">Price</TableHead>
                <TableHead className="text-right">Expected Ret</TableHead>
                <TableHead className="text-right">
                  <Tooltip>
                    <TooltipTrigger className="flex items-center gap-1 ml-auto">Confidence <Info className="h-3 w-3 text-quant-textMuted" /></TooltipTrigger>
                    <TooltipContent>
                      <p>Aggregated ML model prediction confidence.</p>
                      <p>Scores above 85% strongly indicate trend persistence.</p>
                    </TooltipContent>
                  </Tooltip>
                </TableHead>
                <TableHead className="text-right">Target</TableHead>
                <TableHead className="text-right">Stop Loss</TableHead>
                <TableHead>Strategy</TableHead>
                <TableHead>Risk</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {MOCK_SIGNALS.map((sig, i) => (
                <TableRow key={i}>
                  <TableCell>
                    <Dialog>
                      <DialogTrigger className="font-bold text-zinc-200 hover:text-white underline decoration-zinc-600 underline-offset-4 cursor-pointer">{sig.symbol}</DialogTrigger>
                      <DialogContent>
                        <DialogHeader>
                          <DialogTitle>{sig.symbol} Signal Intelligence</DialogTitle>
                          <DialogDescription>Mock data generated by the quantitative ranking engine.</DialogDescription>
                        </DialogHeader>
                        <div className="space-y-4 text-sm mt-4">
                          <div className="flex justify-between border-b border-zinc-800 pb-2">
                            <span className="text-quant-textSecondary">Primary Signal</span>
                            <span className={sig.signal === "BUY" ? "text-quant-bull" : sig.signal === "SELL" ? "text-quant-bear" : "text-zinc-200"}>{sig.signal}</span>
                          </div>
                          <div className="flex justify-between border-b border-zinc-800 pb-2">
                            <span className="text-quant-textSecondary">Expected Return</span>
                            <span className="font-mono text-zinc-200">{(sig.expectedReturn * 100).toFixed(2)}%</span>
                          </div>
                          <div className="flex justify-between border-b border-zinc-800 pb-2">
                            <span className="text-quant-textSecondary">Target</span>
                            <span className="font-mono text-zinc-200">{sig.target.toFixed(2)}</span>
                          </div>
                          <div className="flex justify-between border-b border-zinc-800 pb-2">
                            <span className="text-quant-textSecondary">Stop Loss</span>
                            <span className="font-mono text-zinc-200">{sig.stopLoss.toFixed(2)}</span>
                          </div>
                        </div>
                      </DialogContent>
                    </Dialog>
                  </TableCell>
                  <TableCell>
                    <Badge variant={sig.signal === "BUY" ? "bull" : sig.signal === "SELL" ? "bear" : "secondary"}>
                      {sig.signal}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right font-mono">{sig.price.toFixed(2)}</TableCell>
                  <TableCell className={`text-right font-mono ${sig.expectedReturn >= 0 ? 'text-zinc-300' : 'text-zinc-500'}`}>
                    {(sig.expectedReturn * 100).toFixed(2)}%
                  </TableCell>
                  <TableCell className="text-right font-mono text-quant-textSecondary">
                    {(sig.confidence * 100).toFixed(1)}%
                  </TableCell>
                  <TableCell className="text-right font-mono">{sig.target.toFixed(2)}</TableCell>
                  <TableCell className="text-right font-mono">{sig.stopLoss.toFixed(2)}</TableCell>
                  <TableCell className="text-quant-textSecondary text-xs">{sig.strategy}</TableCell>
                  <TableCell>
                    <span className={`text-xs ${sig.risk === 'High' ? 'text-zinc-500 font-bold' : 'text-quant-textSecondary'}`}>
                      {sig.risk}
                    </span>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
