import React, { useEffect, useState } from "react";
import { ArrowLeft, TrendingUp, ShieldAlert, Cpu, Activity, BarChart2, Info } from "lucide-react";
import { api } from "../api/client";
import { LoadingState, ErrorState } from "../components/ErrorState";
import { StatusBadge } from "../components/StatusBadge";
import { MetricCard } from "../components/MetricCard";
import { PriceChart } from "../charts/PriceChart";
import type { StockDetail as StockDetailType } from "../types";

interface StockDetailProps {
  symbol: string;
  onBack: () => void;
}

export const StockDetail: React.FC<StockDetailProps> = ({ symbol, onBack }) => {
  const [data, setData] = useState<StockDetailType | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchDetail = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await api.getStockDetail(symbol);
      setData(res);
    } catch (err: any) {
      setError(err?.message || `Failed to load intelligence telemetry for ${symbol}.`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDetail();
  }, [symbol]);

  if (loading) return <LoadingState message={`Analyzing quantitative features & historical bars for ${symbol}...`} />;
  if (error || !data) return <ErrorState message={error || "Stock not found."} onRetry={fetchDetail} />;

  const isUp = data.day_change >= 0;

  return (
    <div className="space-y-6">
      {/* Back button & Stock Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 border-b border-quant-border pb-4">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="p-2 bg-quant-card hover:bg-quant-surface border border-quant-border rounded-lg text-quant-textSecondary hover:text-quant-textPrimary transition-colors"
            title="Return to previous view"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>

          <div>
            <div className="flex items-center gap-2.5">
              <h2 className="font-mono text-2xl font-black text-quant-textPrimary">
                {data.symbol}
              </h2>
              <span className="text-xs font-mono font-medium px-2 py-0.5 rounded bg-quant-card border border-quant-border text-quant-textSecondary">
                NSE
              </span>
              <span className="text-xs font-mono font-medium px-2 py-0.5 rounded bg-quant-card border border-quant-border text-quant-cyan">
                {data.sector}
              </span>
              <StatusBadge status={data.risk.risk_status} size="sm" />
            </div>
            <p className="text-xs text-quant-textSecondary mt-0.5">
              {data.company_name} {data.isin && `• ISIN: ${data.isin}`}
            </p>
          </div>
        </div>

        {/* Current Price & Day Change */}
        <div className="text-left sm:text-right font-mono">
          <div className="text-2xl font-black text-quant-textPrimary">
            ₹{data.price.toFixed(2)}
          </div>
          <div className={`text-xs font-bold ${isUp ? "text-quant-bull" : "text-quant-bear"}`}>
            {isUp ? `+₹${data.day_change.toFixed(2)} (+${data.day_change_pct.toFixed(2)}%)` : `-₹${Math.abs(data.day_change).toFixed(2)} (${data.day_change_pct.toFixed(2)}%)`}
            <span className="text-quant-textMuted font-normal ml-1">Today</span>
          </div>
        </div>
      </div>

      {/* Top Intelligence KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <MetricCard
          title="QUANT OPPORTUNITY SCORE"
          value={data.quant_score !== null && data.quant_score !== undefined ? `${data.quant_score.toFixed(1)} / 100` : "N/A"}
          subtitle="Cross-Sectional Rank Model"
          tooltip="Composite quantitative score combining 5-day return prediction, 14-day RSI momentum, and 20-day volatility."
          accentColor="cyan"
        />

        <MetricCard
          title="5-DAY FORWARD ML PRED"
          value={
            data.predicted_return_5d !== null && data.predicted_return_5d !== undefined
              ? `${data.predicted_return_5d >= 0 ? "+" : ""}${(data.predicted_return_5d * 100).toFixed(2)}%`
              : "N/A"
          }
          subtitle={
            data.confidence !== null && data.confidence !== undefined
              ? `Confidence: ${(data.confidence * 100).toFixed(0)}%`
              : "Prediction Unavailable"
          }
          tooltip="Out-of-sample expected forward return generated by expanding-window RandomForest."
          accentColor={
            data.predicted_return_5d !== null && data.predicted_return_5d !== undefined
              ? data.predicted_return_5d >= 0
                ? "bull"
                : "bear"
              : "default"
          }
        />

        <MetricCard
          title="14-DAY RSI MOMENTUM"
          value={data.features.rsi_14.toFixed(1)}
          subtitle={data.features.rsi_14 >= 60 ? "Overbought / Strong" : data.features.rsi_14 <= 40 ? "Oversold / Weak" : "Neutral Range"}
          tooltip="Standard 14-period Relative Strength Index."
          accentColor="default"
        />

        <MetricCard
          title="ANNUALIZED VOLATILITY"
          value={`${data.features.volatility_20d_ann.toFixed(1)}%`}
          subtitle="20-Day Realized Volatility"
          tooltip="Annualized standard deviation of daily logarithmic price returns."
          accentColor="default"
        />
      </div>

      {/* Price Candlestick Chart */}
      <div className="quant-card p-4 space-y-2">
        <div className="flex items-center justify-between pb-2 border-b border-quant-border">
          <div className="flex items-center gap-2">
            <BarChart2 className="w-4 h-4 text-quant-cyan" />
            <h3 className="font-mono text-xs font-bold text-quant-textPrimary">
              HISTORICAL OHLCV CANDLESTICK & VOLUME CHART
            </h3>
          </div>
          <span className="text-[11px] font-mono text-quant-textMuted">
            Source: Apache Parquet Historical Ledger (Last {data.bars.length} Sessions)
          </span>
        </div>

        <PriceChart bars={data.bars} height={320} />
      </div>

      {/* Grid: Features Breakdown & Risk Information */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Quantitative Features Breakdown */}
        <div className="quant-card p-4">
          <h3 className="font-mono text-xs font-bold text-quant-textPrimary flex items-center gap-2 pb-3 border-b border-quant-border mb-3">
            <Activity className="w-4 h-4 text-quant-cyan" />
            ENGINEERED FEATURE BREAKDOWN (STEP 4)
          </h3>

          <div className="space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">14-Day RSI (Momentum):</span>
              <span className="font-bold text-quant-textPrimary">{data.features.rsi_14.toFixed(2)}</span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">20-Day Annualized Volatility:</span>
              <span className="font-bold text-quant-textPrimary">{data.features.volatility_20d_ann.toFixed(2)}%</span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Volume to 20-Day SMA Ratio:</span>
              <span className="font-bold text-quant-textPrimary">{data.features.volume_ratio_20d.toFixed(2)}x</span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">5-Day Relative Strength:</span>
              <span className={`font-bold ${data.features.relative_strength_5d >= 0 ? "text-quant-bull" : "text-quant-bear"}`}>
                {data.features.relative_strength_5d >= 0 ? `+${data.features.relative_strength_5d.toFixed(2)}%` : `${data.features.relative_strength_5d.toFixed(2)}%`}
              </span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Latest Session Volume:</span>
              <span className="font-bold text-quant-textPrimary">{data.volume.toLocaleString("en-IN")} shares</span>
            </div>
          </div>
        </div>

        {/* Risk & Portfolio Status */}
        <div className="quant-card p-4">
          <h3 className="font-mono text-xs font-bold text-quant-textPrimary flex items-center gap-2 pb-3 border-b border-quant-border mb-3">
            <ShieldAlert className="w-4 h-4 text-quant-warn" />
            RISK & PORTFOLIO CONCENTRATION
          </h3>

          <div className="space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Max Single-Stock Limit:</span>
              <span className="font-bold text-quant-textPrimary">{data.risk.max_allowed_weight_pct.toFixed(1)}%</span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Current Portfolio Weight:</span>
              <span className={`font-bold ${data.risk.current_portfolio_weight_pct > 35 ? "text-quant-bear" : "text-quant-textPrimary"}`}>
                {data.risk.current_portfolio_weight_pct.toFixed(2)}%
              </span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Shares Held in Paper Ledger:</span>
              <span className="font-bold text-quant-cyan">{data.risk.shares_owned} shares</span>
            </div>

            <div className="flex items-center justify-between p-2 rounded bg-quant-surface border border-quant-border">
              <span className="text-quant-textSecondary">Risk Engine Verdict:</span>
              <StatusBadge status={data.risk.risk_status} size="sm" />
            </div>

            <div className="p-2.5 rounded bg-quant-surface border border-quant-border text-[11px] text-quant-textMuted leading-relaxed">
              <span className="text-quant-cyan font-bold">Trading Note: </span>
              Positions are evaluated point-in-time prior to trade submission. If current weight exceeds the 35% cap, buy orders are automatically blocked by the 12-point pre-trade risk engine.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
